Fix the Missing a Javadoc comment problem during compilation
fix problem during compilation :

Error: java: JavadocType: Missing a Javadoc comment.

The solution is to add comment to the class