[hotfix][cdc-common] Fix NoSuchMethodError of CollectionUtil.newHashMapWithExpectedSize
This closes #2943

(cherry picked from commit 146ed9d0bea5446040a92d5bd51aef16a4c19f7b)