Revert "Upgrade testcontainers dependency to 1.16.2 (#591)"
We have to fallback to v1.15.3 testcontainers, because Azure Pipeline always complaining the following error when starting the container:

```
04:18:43,894 [main] INFO  🐳 [jark/oracle-xe-11g-r2-cdc:0.1]                           [] - Waiting for database connection to become available at jdbc:oracle:thin:system/oracle@localhost:49165:xe using query 'SELECT 1 FROM DUAL'
04:18:43,949 [docker-java-stream--1472620850] INFO  com.ververica.cdc.connectors.e2e.OracleE2eITCase             [] - STDOUT: Starting Oracle Net Listener.
04:18:44,102 [docker-java-stream--1472620850] INFO  com.ververica.cdc.connectors.e2e.OracleE2eITCase             [] - STDOUT: Starting Oracle Database 11g Express Edition instance.
04:18:58,842 [docker-java-stream--1472620850] INFO  com.ververica.cdc.connectors.e2e.OracleE2eITCase             [] - STDOUT:
04:22:44,218 [main] ERROR 🐳 [jark/oracle-xe-11g-r2-cdc:0.1]                           [] - Could not start container
java.lang.IllegalStateException: Container is started, but cannot be accessed by (JDBC URL: jdbc:oracle:thin:system/oracle@localhost:49165:xe), please check container logs
```

According to this issue[1], this might be a problem of Oracle testcontainers v1.16 working with "wnameless/oracle-xe-11g-r2".
A better solution might be upgrade our Oracle base image to "gvenzl/oracle-xe" which is the default image of Oracle testcontainers v1.16.

[1]: https://github.com/testcontainers/testcontainers-java/issues/4297